<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\lib\\factory\\sample\\filelogger' => '/FileLogger.php',
                'theseer\\lib\\factory\\sample\\locatorfactory' => '/LocatorFactory.php',
                'theseer\\lib\\factory\\sample\\loggerfactory' => '/LoggerFactory.php',
                'theseer\\lib\\factory\\sample\\loggerinterface' => '/LoggerInterface.php',
                'theseer\\lib\\factory\\sample\\loggerlocator' => '/LoggerLocator.php',
                'theseer\\lib\\factory\\sample\\nulllogger' => '/NullLogger.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd