<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\lib\\factory\\abstractchildfactorytest' => '/AbstractChildFactoryTest.php',
                'theseer\\lib\\factory\\extendedstubchildfactory' => '/_stubs/ExtendedStubChildFactory.php',
                'theseer\\lib\\factory\\masterfactorytest' => '/MasterFactoryTest.php',
                'theseer\\lib\\factory\\stubabstractchildfactory' => '/_stubs/StubAbstractChildFactory.php',
                'theseer\\lib\\factory\\stubchildfactory' => '/_stubs/StubChildFactory.php',
                'theseer\\lib\\factory\\testclass' => '/_stubs/TestClass.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd