<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\lib\\factory\\sample\\dependency' => '/Dependency.php',
                'theseer\\lib\\factory\\sample\\dependencysamplechildfactory' => '/DependencySampleFactory.php',
                'theseer\\lib\\factory\\sample\\samplechildfactory' => '/SampleChildFactory.php',
                'theseer\\lib\\factory\\sample\\something' => '/FileLogger.phpp'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd