<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\lib\\factory\\sample\\abtestfactory' => '/ABTestFactory.php',
                'theseer\\lib\\factory\\sample\\alternativehelper' => '/AlternativeHelper.php',
                'theseer\\lib\\factory\\sample\\defaulthelper' => '/DefaultHelper.php',
                'theseer\\lib\\factory\\sample\\samplefactory' => '/SampleFactory.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd